In [2]:
import pandas as pd
import numpy as np

pokemon = pd.read_csv("data/pokemon_complete.csv")
types = pd.read_csv("data/pokemon_types.csv")

In [3]:
pokemon.head()

,pokedex_number,name,type_1,type_2,hp,attack,defense,sp_attack,sp_defense,speed,...,shape,egg_groups,habitat,growth_rate,capture_rate,base_happiness,genus,evolution_chain_id,flavor_text,sprite_url
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,...,quadruped,monster|plant,grassland,medium-slow,45,70,Seed Pokémon,1,A strange seed was planted on its back at birt...,https://raw.githubusercontent.com/PokeAPI/spri...
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,...,quadruped,monster|plant,grassland,medium-slow,45,70,Seed Pokémon,1,"When the bulb on its back grows large, it appe...",https://raw.githubusercontent.com/PokeAPI/spri...
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,...,quadruped,monster|plant,grassland,medium-slow,45,70,Seed Pokémon,1,The plant blooms when it is absorbing solar en...,https://raw.githubusercontent.com/PokeAPI/spri...
3,4,Charmander,Fire,NaN,39,52,43,60,50,65,...,upright,monster|dragon,mountain,medium-slow,45,70,Lizard Pokémon,2,"Obviously prefers hot places. When it rains, s...",https://raw.githubusercontent.com/PokeAPI/spri...
4,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,...,upright,monster|dragon,mountain,medium-slow,45,70,Flame Pokémon,2,"When it swings its burning tail, it elevates t...",https://raw.githubusercontent.com/PokeAPI/spri...

In [7]:
pokemon.shape

(1350, 31)

In [8]:
types.head()

,type,double_damage_to,half_damage_to,no_damage_to,double_damage_from,half_damage_from,no_damage_from
0,normal,NaN,rock|steel,ghost,fighting,NaN,ghost
1,fighting,normal|rock|steel|ice|dark,flying|poison|bug|psychic|fairy,ghost,flying|psychic|fairy,rock|bug|dark,NaN
2,flying,fighting|bug|grass,rock|steel|electric,NaN,rock|electric|ice,fighting|bug|grass,ground
3,poison,grass|fairy,poison|ground|rock|ghost,steel,ground|psychic,fighting|poison|bug|grass|fairy,NaN
4,ground,poison|rock|steel|fire|electric,bug|grass,flying,water|grass|ice,poison|rock,electric

In [10]:
types.shape

(18, 7)